version: '3'
services:
  mongodb:
    image: 'mongo:3.3'
    container_name: "mongo-container"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - rsvpnet

  spring:
    image: shanureddy78/webapikaiburr:master-4931899
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mongos
      MONGO_HOST: mongodb
    ports:
      - "8080:8080"
    networks:
      - rsvpnet

networks:
  rsvpnet:

volumes:
  db_data:
