version: '3'
services:
  mongodb:
    image: 'mongo:4.2'
    container_name: "mongo-container"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shanu
      - MONGO_INITDB_ROOT_PASSWORD=shanu
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - rsvpnet

  spring:
    image: shanureddy78/webapikaiburr:master-29dbb41
    environment:
      - MONGOUSER=shanu
      - MONGOPASS=shanu
      - MONGODB=mongos
      - MONGOHOST=mongodb
    ports:
      - "8080:8080"
    networks:
      - rsvpnet

networks:
  rsvpnet:

volumes:
  db_data:
